### ISSUE TITLE
Ngenic track

### ISSUE THREAD

**Issue by robinostlund** [sfalkman/ngenic-hass-platform#1]
Awesome work, i am wondering if you have the possibility to add support for ngenic track so it could create a sensor for the current usage?

Brg
Robin

**Comment by sfalkman** [comment]
I don't have a Track, so it's a bit hard to debug. Also the ngenic documentation of the API doesn't mention that much about track.

However, if you're able to help maybe we could figure it out anyway.
This project for Home Assistant is depending on the ngenicpy lib, so we need to start there.
Could you install ngenicpy and run a script to figure out some info for me?

Install ngenicpy:
`pip3 install ngenicpy`

Run this (change XXX to your API token):
```
import json
from ngenicpy import Ngenic
from ngenicpy.models.node import NodeType

ngenic = Ngenic(
    token="XXX"
)

for tune in ngenic.tunes():
    for node in tune.nodes():
        if node.get_type() == NodeType.SENSOR:
            print("Device type %s" % (json.dumps(node["device"]["type"])))
            for m in node.measurement_types():
              print("Measurement: %s" % str(m))
```

This should print the device type connected to your sensors and try to print the measurement type, but since I have not defined any measurement type for the Track I suspect the script will fail.
Anyhow, print your output from the script and lets see..

**Comment by robinostlund** [comment]
Oright, will give you some data tomorrow 😀

**Comment by robinostlund** [comment]
This is what it says:
ValueError: 'power_kW' is not a valid MeasurementType

**Comment by sfalkman** [comment]
Perfect, exactly what I wanted :)
I will add it when I get the time, but if you got some extra time you could try it yourself: if you add something like `POWER_KW = "power_KW"` to the `MeasurementType` enum in `ngenicpy/models/measurement.py` and run the script again, do you come around the error then?

If so, I will add it and push a new build, after that I can look into adding it to the hass component.

**Comment by robinostlund** [comment]
Added:
POWER_KW = "power_kW"
Got:
ValueError: 'energi_kWH' is not a valid MeasurementType
Added: 
POWER_KWH = "energi_kWH"
Worked:
Got: 
<ngenicpy.models.node.Node object at 0x10f9a0e80>
<ngenicpy.models.node.Node object at 0x10f9a0e10>
<ngenicpy.models.node.Node object at 0x10f9a0ef0>
Device type 4
Measurement: MeasurementType.TEMPERATURE
Measurement: MeasurementType.TARGET_TEMPERATURE
Measurement: MeasurementType.HUMIDITY
<ngenicpy.models.node.Node object at 0x11044a080>
<ngenicpy.models.node.Node object at 0x11044a240>
Device type 9
Measurement: MeasurementType.POWER_KW
Measurement: MeasurementType.POWER_KWH

Maby should change Power_ kwh to something else?

Note that you wrote POWER_KW = "power_KW" it should be as i wrote "power_kW" :)

/ R

**Comment by robinostlund** [comment]
class MeasurementType(Enum):
    TEMPERATURE = "temperature_C"
    TARGET_TEMPERATURE = "target_temperature_C"
    HUMIDITY = "humidity_relative_percent"
    CONTROL_VALUE = "control_value_C"
    POWER_KW = "power_kW"
    POWER_KWH = "energi_kWH"

**Comment by sfalkman** [comment]
Thanks, I made a couple of changes, could you please test them for me?

On your hass env, checkout the `track` branch:
```
$ git clone https://github.com/sfalkman/ngenic-hass-platform.git ngenic
$ git checkout track
```
This branch will use version `0.1.2b1` of ngenicpy, which includes the measurement types you found.

If you restart hass and check the Ngenic integration - does the new sensors show up?

**Comment by robinostlund** [comment]
Doesn't work but i get another error :) 

```2019-12-08 13:49:11 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform ngenic
  File "/usr/local/lib/python3.7/site-packages/ngenicpy/models/base.py", line 123, in _request
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://app.ngenic.se/api/v3/tunes/9667f840-f8bf-e811-af11-000d3ab14962/measurements/7b3fd937-e9f6-e911-b5e9-000d3ab21589/latest?type=humidity_relative_percent
  File "/config/custom_components/ngenic/sensor.py", line 95, in async_setup_entry
  File "/config/custom_components/ngenic/sensor.py", line 136, in _async_update
  File "/config/custom_components/ngenic/sensor.py", line 142, in _update
  File "/usr/local/lib/python3.7/site-packages/ngenicpy/models/node.py", line 69, in measurement
  File "/usr/local/lib/python3.7/site-packages/ngenicpy/models/base.py", line 102, in _parse_new_instance
  File "/usr/local/lib/python3.7/site-packages/ngenicpy/models/base.py", line 161, in _get
  File "/usr/local/lib/python3.7/site-packages/ngenicpy/models/base.py", line 132, in _request
ngenicpy.exceptions.ClientException: (ClientException(...), 'A request exception occurred: Type humidity_relative_percent is not available for node')```

**Comment by sfalkman** [comment]
Can you try pull the latest from track branch, and try again? Made a copy-paste error.

**Comment by robinostlund** [comment]
Got this now when i started HA:
```2019-12-10 10:54:59 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform ngenic
  File "/usr/local/lib/python3.7/site-packages/ngenicpy/models/base.py", line 123, in _request
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://app.ngenic.se/api/v3/tunes/9667f840-f8bf-e811-af11-000d3ab14962/measurements/7b3fd937-e9f6-e911-b5e9-000d3ab21589/latest?type=power_kW
  File "/config/custom_components/ngenic/sensor.py", line 95, in async_setup_entry
  File "/config/custom_components/ngenic/sensor.py", line 136, in _async_update
  File "/config/custom_components/ngenic/sensor.py", line 142, in _update
  File "/usr/local/lib/python3.7/site-packages/ngenicpy/models/node.py", line 69, in measurement
  File "/usr/local/lib/python3.7/site-packages/ngenicpy/models/base.py", line 102, in _parse_new_instance
  File "/usr/local/lib/python3.7/site-packages/ngenicpy/models/base.py", line 161, in _get
  File "/usr/local/lib/python3.7/site-packages/ngenicpy/models/base.py", line 132, in _request
ngenicpy.exceptions.ClientException: (ClientException(...), 'A request exception occurred: Type power_kW is not supported for latest')```

**Comment by sfalkman** [comment]
Hmm, that's disappointing... What if you remove the `power` sensor then, does the `energy` sensor work?

Can you edit `sensor.py` and remove/comment rows 71-80, then restart hass.

**Comment by robinostlund** [comment]
That seems to work :)
2019-12-10 16:45:26 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ngenic entity: sensor.vardagsrum_humidity_2
2019-12-10 16:45:26 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ngenic entity: sensor.ngenic_sensor_power
2019-12-10 16:45:26 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ngenic entity: sensor.ngenic_controller_temperature
2019-12-10 16:45:26 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ngenic entity: sensor.vardagsrum_temperature_2

**Comment by sfalkman** [comment]
Nice! So you can add it from Integrations?
Is the energy sensor what you searched for? Not sure about the difference of the power and energy measurements, and why we can't get the latest power measurement.

Care to send a screenshot of the entity? :)

**Comment by robinostlund** [comment]
Yes correct i could add it from integrations :)
Energy is the current usage, power is existing usage :) like a counter for the number of kwh that you have used.
Here you can see screenshot of the created sensors: https://www.dropbox.com/s/topzsv39g3q0cdc/Screenshot%202019-12-10%2019.31.20.png?dl=0
And here is an screenshot of "Förbrukning" which should be power_kW: https://www.dropbox.com/s/93cm5f4mf5lv74k/Screenshot%202019-12-10%2019.34.42.png?dl=0

I am wondering if power_kW is not yet implemented in the api with latest, i think this function needs to be used: MinMaxMeasurement as i believe power_kW is time series data.

**Comment by sfalkman** [comment]
So, is kWh the correct unit for the value you are getting for the sensor in hass?

Sorry for late response.

**Comment by robinostlund** [comment]
Well the same value as i have in the app says kW so i guess it should be kW instead of kWh.

**Comment by sfalkman** [comment]
Ok, thanks.

I've made some changes to the ngenicpy lib, could you try installing the beta version and run the script below? It will print the MinMaxMeasurement you mentioned from the current day. Could you compare the measured value to your kWH in the Ngenic app?

`pip3 install ngenicpy==0.1.2b2`

```
import json
import datetime
from ngenicpy import Ngenic
from ngenicpy.models.node import NodeType

ngenic = Ngenic(
    token="XXX"
)

from_dt = datetime.datetime.now().replace(hour=0, minute=0, second=0, microsecond=0).isoformat() + "Z"
to_dt = datetime.datetime.now().replace(hour=23, minute=59, second=59, microsecond=0).isoformat() + "Z"

for tune in ngenic.tunes():
    for node in tune.nodes():
        if node.get_type() == NodeType.SENSOR:
            print("Device type %s" % (json.dumps(node["device"]["type"])))
            for m in node.measurement_types():
              print("Measurement: %s" % str(m))
              try:
                measured = node.measurement(m, from_dt, to_dt)
                for mesh in measured:
                  print("Measured: %s" % mesh.json())
              except Exception as e:
                print(str(e))
                pass
```

**Comment by Gamester17** [comment]
Great of you for publicly publishing your work on Ngenic Tune and now Ngenic Track on GitHub!

Please excuse me if this is the wrong forum for this question but I'm a Ngenic Tune owner and wondering if you guys would recommend buying the new Ngenic Track energy meter reader if I am also a Home Assistant user? 

We live in a large house (with poor isolation) that uses an old geothermal heating-pump for heating and I really like Ngenic Tune as it made our dumb heating-pump into a smart appliance. 

My home automation budget is a little tight right now but I received an advertisement e-mail from them giving 10% off if use "tracktack" as the coupon code, with that offer being valid until the 31th of December 2019. 

At least I have a good practical excuse to buy this as another toy to play with as when we got our last energy bill my girlfriend recently asked if we could keep a better eye on our energy meter readings to make sure we are not being scammed.

Thank you regardless for publicly working on code for Ngenic Tune and now Ngenic Track on GitHub!

**Comment by sfalkman** [comment]
Sorry @Gamester17, but I can't recommend one because I don't have an Ngenic Track myself.

Hoping @robinostlund would provide some additional info from the instructions above so we could further investigate how the Ngenic Track works.

**Comment by robinostlund** [comment]
Sorry for late answer:
Device type 4
Measurement: MeasurementType.TEMPERATURE
Measured: {'hasValue': True, 'max': 21.6875, 'min': 21.0, 'time': '2020-01-07T00:00:00 Etc/UTC', 'value': 21.307905197143555}
Measurement: MeasurementType.TARGET_TEMPERATURE
Measured: {'hasValue': True, 'max': 21.5, 'min': 21.5, 'time': '2020-01-07T00:00:00 Etc/UTC', 'value': 21.5}
Measurement: MeasurementType.HUMIDITY
Measured: {'hasValue': True, 'max': 48.0, 'min': 46.0, 'time': '2020-01-07T00:00:00 Etc/UTC', 'value': 47.088233947753906}
Device type 9
Measurement: MeasurementType.POWER_KW
(ClientException(...), "A request exception occurred: Type power_kW require a 'period' parameter in request")
Measurement: MeasurementType.ENERGY_KWH
Measured: {'hasValue': True, 'max': None, 'min': None, 'time': '2020-01-07T00:00:00Z', 'value': 18.0}

And that seems to be correct

**Comment by robinostlund** [comment]
I emailed an own token for you to test with for my account :)

**Comment by sfalkman** [comment]
Could you try to pull the latest changes from the `track` branch?
I.e. do what you did before:
```
$ git clone https://github.com/sfalkman/ngenic-hass-platform.git ngenic
$ git checkout track
```

I've tested this and it seems to work, but it would be nice if you can double check against the Ngenic app that the values are correct.

If this looks good to you, I will merge the changes into master.

**Comment by robinostlund** [comment]
Tested it now, in app it says 75 kwh today, but 72 kwh in the sensor. Is the request in CET time? Just wondering if it could be something with timezone.

**Comment by robinostlund** [comment]
Now it works, it says 62 kwh in ha and 62 i app :)

**Comment by sfalkman** [comment]
Track support have been merged to the master branch, don't forget to switch back to that branch in you hass setup :)

Thanks a lot for your help!
