### ISSUE TITLE
Deprecated warning ".translation" 

### ISSUE THREAD

**Issue by JohNan** [sfalkman/ngenic-hass-platform#12]
Hi, 

I got this message in my log.

> ngenic: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this

Better be prepared than sorry 😉

**Comment by sfalkman** [comment]
Made a copy of the `.translations` folder, and keeping the old folder to be backwards compatible.
