### ISSUE TITLE
Deprecated warning: ClimateDevice is deprecated

### ISSUE THREAD

**Issue by JohNan** [sfalkman/ngenic-hass-platform#14]
I get a deprecated warning in the logs. It should be fairly easy to get rid of. 

`ClimateDevice is deprecated, modify NgenicTune to extend ClimateEntity`

**Comment by JohNan** [comment]
I created a PR for you: https://github.com/sfalkman/ngenic-hass-platform/pull/15

**Comment by sfalkman** [comment]
Merged #15, thanks!
