### ISSUE TITLE
Error setting up entities after adding an Ngenic Track

### ISSUE THREAD

**Issue by niklaskb** [sfalkman/ngenic-hass-platform#16]
Getting this error after adding the integration.
It creates only a climate.ngenic_tune_XXX entity, all other entities are missing.
Possibly related to adding an Ngenic Track.

```
Logger: homeassistant.components.sensor
Source: custom_components/ngenic/sensor.py:343
Integration: Sensor (documentation, issues)
First occurred: 21:22:19 (1 occurrences)
Last logged: 21:22:19
Error while setting up ngenic platform for sensor

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ngenicpy/models/base.py", line 60, in _parse
    rsp_json = response.json()
  File "/usr/local/lib/python3.8/site-packages/httpx/_models.py", line 856, in json
    return jsonlib.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/ngenic/sensor.py", line 175, in async_setup_entry
    await device._async_update()
  File "/config/custom_components/ngenic/sensor.py", line 228, in _async_update
    new_state = await self._async_fetch_measurement()
  File "/config/custom_components/ngenic/sensor.py", line 343, in _async_fetch_measurement
    current = await self._node.async_measurement(self._measurement_type, from_dt, to_dt)
  File "/usr/local/lib/python3.8/site-packages/ngenicpy/models/node.py", line 144, in async_measurement
    return await self._async_parse_new_instance(url, Measurement, node=self, measurement_type=measurement_type)
  File "/usr/local/lib/python3.8/site-packages/ngenicpy/models/base.py", line 119, in _async_parse_new_instance
    ret_json = self._parse(await self._async_get(url))
  File "/usr/local/lib/python3.8/site-packages/ngenicpy/models/base.py", line 62, in _parse
    raise ApiException("Ngenic API return an invalid json body")
ngenicpy.exceptions.ApiException: Ngenic API return an invalid json body
```

**Comment by niklaskb** [comment]
Looks like it's related to the query types for the Ngenic Track:

```
curl -X GET \
  -H "Authorization: Bearer 0123456789abcdef0123456789abcdef" \
  "https://app.ngenic.se/api/v3/tunes/{tuneUuid}/measurements/{nodeUuid}/types"
```
returns `["power_kW","energi_kWH"]`

But
```
curl -X GET \
-H "Authorization: Bearer 0123456789abcdef0123456789abcdef" \
"https://app.ngenic.se/api/v3/tunes/{tuneUuid}/measurements/{nodeUuid}/latest?type=energi_kWH"
```
Gives a bad request, stating that `Type energi_kWH is not supported for latest"`

**Comment by niklaskb** [comment]
Looks like this problem only applies to the NgenicEnergySensorLastMonth.
If I remove the sensor from here it works (except that sensor of course): https://github.com/sfalkman/ngenic-hass-platform/blob/365bdd011f5a10e3e484f0178bc788b2b44c77d9/custom_components/ngenic/sensor.py#L162

I've just installed Ngenic Track so there is no data for last month which potentially could cause the problem?

**Comment by sfalkman** [comment]
Hey, sorry for the late reply.
Unfortunately I don't have a Track to debug with, I've had a lot of help from other contributors to implement the track support.

However, it sounds like you're on to something.
@patrik3k if you have the time, could you try to manually get the latest readings from a time when you didn't have your Tune installed, to see if it produces the same error as @niklaskb?

**Comment by patrik3k** [comment]
Hi, my python skills are at best a very low level but Ill try look into it this week.

Mvh, (kortfattat från mobilen)
Patrik Ekström

**Comment by sfalkman** [comment]
No need for python really, you could make your way with curl.

Replace the X with your API token

Get tuneUuid from
`curl -v -X GET https://app.ngenic.se/api/v3/tunes/ -H "Authorization: Bearer XXXXXX"`

Find the uuid of your Track sensor (it should have `type: 0`)
`curl -v -X GET https://app.ngenic.se/api/v3/tunes/TUNE-UUID/gateway/nodes -H "Authorization: Bearer XXXXXX"`

Get the measurements (I'm not entirely sure about this command, I didn't get it to work with temperature but that is probably expected):
`curl -v -X GET https://app.ngenic.se/api/v3/tunes/TUNE-UUID/measurements/NODE-UUID/?type=energi_kWH&from=2020-09-01T00:00:00Z&to=2020-10-01T00:00:00Z -H "Authorization: Bearer XXXXXX"`

Make sure the last query works, then try to replace the `from` and `to` in the last query with a date from 2018 or something and see what the result it.

@niklaskb you could try the same thing, but replacing the dates with a span where you had your track installed.

**Comment by niklaskb** [comment]
> @niklaskb you could try the same thing, but replacing the dates with a span where you had your track installed.

* A date range before I installed the Track gives me a HTTP 204 response with an empty body.
* A date range after the install gives me HTTP 200 with this body:
```[{"hasValue":true,"max":null,"min":null,"time":"2020-10-25T00:00:00Z","value":72.0}]```
 * A date range that spans both the time before and after the instal gives me this body:
```[{"hasValue":true,"max":null,"min":null,"time":"2020-09-25T00:00:00Z","value":233.00048828125}]```

**Comment by sfalkman** [comment]
Thanks! That seems to be the issue then, the ngenicpy lib tries to blindly parse JSON from any successful request and if there are no JSON in the response it will throw an exception.

It feels like a bug in the API to return a 204 (No Content) response when it has a property called `hasValue` (documented as _Whether a value is present in the Measurement period._).

I guess the best solution to work around this is to let ngenicpy check if the response is a 204, and if so, create fake values for the `Measurement` class. This could in its turn be checked against on the hass-component side.

E.g.
```json
[{
  "hasValue": false,
  "max": null,
  "min": null,
  "time": "<from-date>",
  "value": null
}]
```

I'll try to find time to fix this ASAP, but as I said, it's a bit hard to debug without a track.

**Comment by sfalkman** [comment]
@niklaskb could you test the changes I've made in this branch: https://github.com/sfalkman/ngenic-hass-platform/tree/issue-16
You'll have to replace your `sensor.py` and `manifest.json`.

The _last month energy_ entity should display as 0.

**Comment by niklaskb** [comment]
> @niklaskb could you test the changes I've made in this branch

I'm getting this error when setting it up now:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/ngenic/sensor.py", line 201, in async_setup_entry
    await device._async_update()
  File "/config/custom_components/ngenic/sensor.py", line 254, in _async_update
    new_state = await self._async_fetch_measurement()
  File "/config/custom_components/ngenic/sensor.py", line 366, in _async_fetch_measurement
    current = await get_measurement_value(self._node, measurement_type=self._measurement_type, from_dt=from_dt, to_dt=to_dt)
  File "/config/custom_components/ngenic/sensor.py", line 95, in get_measurement_value
    kwargs.get(measurement_type, "unknown"),
NameError: name 'measurement_type' is not defined
```

**Comment by sfalkman** [comment]
@niklaskb finally got my own Track so I could debug this myself.
If you update the component it should now work.

**Comment by niklaskb** [comment]
Excellent! Thanks for the fix!
