### ISSUE TITLE
[REQUEST] Support for "Ngenic Track" product wireless energy meter reader

### ISSUE THREAD

**Issue by Gamester17** [sfalkman/ngenic-hass-platform#2]
Please consider adding support for their new "Ngenic Track" product (a wireless energy meter reader)

https://ngenic.se/track/

Ngenic Track sensor connects to the same gateway plus uses the same API and app.

As Ngenic is a cloud based service so it includes data history of your energy usage as long as had it.

**Comment by Gamester17** [comment]
@sfalkman Swedish: Alla kunder har fått mail med 10% rabattkod "tracktack" (t.o.m. 31 dec 2019).

**Comment by sfalkman** [comment]
We're discussing Track support over here: https://github.com/sfalkman/ngenic-hass-platform/issues/1
You're welcome to help out with the debugging if you got a track :)

**Comment by Gamester17** [comment]
Cool, thanks! I have not yet bought/ordered one yet though but I am considering it still
