### ISSUE TITLE
No entities shows up after install

### ISSUE THREAD

**Issue by pewi72** [sfalkman/ngenic-hass-platform#21]
Ngenic stopped working yesterday, i made a new install and get the following error in the logfile.
No entities shows up under integration.

Supervisor
Version
2020.12.7

Logger: homeassistant.components.sensor
Source: custom_components/ngenic/sensor.py:130
Integration: Sensor (documentation, issues)
First occurred: 10:16:51 AM (1 occurrences)
Last logged: 10:16:51 AM

Error while setting up ngenic platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/ngenic/sensor.py", line 130, in async_setup_entry
    measurement_types = await node.async_measurement_types()
  File "/usr/local/lib/python3.8/site-packages/ngenicpy/models/node.py", line 54, in async_measurement_types
    self._measurementTypes = list(MeasurementType(m) for m in measurements)
  File "/usr/local/lib/python3.8/site-packages/ngenicpy/models/node.py", line 54, in <genexpr>
    self._measurementTypes = list(MeasurementType(m) for m in measurements)
  File "/usr/local/lib/python3.8/enum.py", line 315, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 617, in __new__
    raise ve_exc
ValueError: 'energy_kWH' is not a valid MeasurementType

**Comment by patrik3k** [comment]
This is the same issue as #20. 

This specific exception 
ValueError: 'energy_kWH' is not a valid MeasurementType

is because the energy_kWH was named energi_kWH before and they changed the name in the API. The ngenic people is probably Swedish or Norwegian where energy is spelled energi:)

**Comment by patrik3k** [comment]
A workaround is to change the file ngenicpy/models/measurement.py and the enum below.

class MeasurementType(Enum):
TEMPERATURE = "temperature_C"
TARGET_TEMPERATURE = "target_temperature_C"
HUMIDITY = "humidity_relative_percent"
CONTROL_VALUE = "control_value_C"
POWER_KW = "power_kW"
#CHANGE
ENERGY_KWH = "energy_kWH"
#ADD
FLOW_L_PER_H = "flow_litre_per_hour"
INLET_FLOW_TEMP_C = "inlet_flow_temperature_C"
RETURN_TEMP_C = "return_temperature_C"

**Comment by pewi72** [comment]
Thanks for your quick reply, where can i find the folder that holds the measurement.py

**Comment by patrik3k** [comment]
Without any proper background info, for me its in the deps folder which probably means its an external package that HA integration imports. 

/Users/patrik/.homeassistant/deps/lib/python/site-packages/ngenicpy/models/measurement.py

Mvh/Regards
Patrik Ekström

**Comment by pewi72** [comment]
Thanks !!
