### ISSUE TITLE
Version key required in manifest file after Home Assistant 2021.3

### ISSUE THREAD

**Issue by LinusT** [sfalkman/ngenic-hass-platform#28]
After the upgrade to HASS 2021.3 this error occurs in the log.

WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'ngenic'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'ngenic'

Seems to be a trivial update to the manifest needed. But I have no time to investigate atm.

**Comment by sfalkman** [comment]
Thanks for reporting this, hadn't noticed it. Let's call it 1.0.0 :)  
Fixed here: https://github.com/sfalkman/ngenic-hass-platform/pull/29

**Comment by LinusT** [comment]
Brilliant! :-)
