### ISSUE TITLE
Can't install via integrations

### ISSUE THREAD

**Issue by alexhardwicke** [sfalkman/ngenic-hass-platform#39]
I added the repository to HACS and it correctly detected the repository/versions, so I installed the latest release (2.0.0). I also afterwards tried a manual git clone and am having the same issue. The files all look correct in custom_components/ngenic.

home-assistant.log shows that the component is detected (there's the line "We found a custom integration ngenic which has not been tested by Home Assistant...") and no other entries related to ngenic.

The issue is simply that I can't install the integration via home assistant - when I choose "Add" in integrations, ngenic doesn't appear as a choice I can select. My assumption is that something has changed for config flow in the latest version of Home Assistant (I'm running 2021.12).

**Comment by alexhardwicke** [comment]
Works again as of home assistant 2021.12.2!

**Comment by sfalkman** [comment]
Ah, missed your second comment. Was just scratching my head because it was working for me at 2021.12.2 as well :)
