### ISSUE TITLE
Integration not available

### ISSUE THREAD

**Issue by newlund** [sfalkman/ngenic-hass-platform#41]
Trying to add the integration via UI: Configuration > Integrations
Installed via HACS
Searching for ngenic shows nothing.
Running Home Assistant 2022.2.6

**Comment by sfalkman** [comment]
I haven't tested on 2022.2.6, do you get any logs indicating an issue?

**Comment by newlund** [comment]
Sorry, now I tried on my mobile phone and it appeared in the list.
After a browser refresh on my computer it showed up. Sorry, should have tried that before submitting an issue.
All fine now. Thank you for this integration! :)
