### ISSUE TITLE
Feature request: Simulate heat pump on or off

### ISSUE THREAD

**Issue by Brandyellow** [sfalkman/ngenic-hass-platform#45]
When the spring comes and the house no longer needs heating, I and I am sure many with me are turning off the house heating ability on the heat pump, leaving only the water heating ability on.

Ngenic Tune has no way of knowing this, but for different purposes in Home Assistant there might be good to know this.

I propose to add a boolean sensor for Ngenic Tune that can be set on or off from Home Assistant and is stored locally.
This way a Home Assistant user can use this sensor to check if the heat pump is on or off, and perform automations and dashboard building based on it. 

Examples of ways to use this sensor:

- Stop adjusting the control temperature if heat pump is off
- Warn the user if the heat pump is off and indoor temperature is getting low
- Only show the thermostat card on the dashboard if the heat pump is on
- ...

**Comment by sfalkman** [comment]
Since you don't propose any actual logic to this sensor, it doesn't have anything to do with this integration.  
You can easily add a binary sensor yourself and write logic around that.

https://www.home-assistant.io/integrations/binary_sensor/
