### ISSUE TITLE
Can't get access token

### ISSUE THREAD

**Issue by SonnySWE** [sfalkman/ngenic-hass-platform#49]
I've come to the step when I need to enter the access token, but when I go to get one I can't seem to log in.
Can it have something to do with ngenic separating into perific & enegic?

**Comment by sfalkman** [comment]
Not sure what you mean.. Perific/Enegic is not the same as Ngenic

**Comment by SonnySWE** [comment]
Truly sorry...
You are of course correct.. 
I was tired and got it mixed up in the rush of just starting with HA..

**Comment by sfalkman** [comment]
No worries :)  
You can generate an Ngenic token here (if it's Ngenic you're using): https://developer.ngenic.se/tokens
