### ISSUE TITLE
HACS compatibility

### ISSUE THREAD

**Issue by JohNan** [sfalkman/ngenic-hass-platform#9]
Hi,

I tried adding this repository to HACS but it is not compatible. I would really appreciate if you could add support for it. It makes it a lot easier to add to Home Assistant and to keep updated. You can find the instructions on this page https://hacs.xyz/docs/publish/integration

**Comment by sfalkman** [comment]
Good idea! I haven't used HACS, so I'll install it and modify the component to work with it as soon as I got the time.

Basically, it looks like I only need to move the code to `custom_components/ngenic/` and add an `info.md` in the root

**Comment by JohNan** [comment]
Thanks! 
Yes, it's really easy to get it working. HACS is really neat. Makes so much easier to add and update third-party integrations.

I was thinking about making a PR, we'll see who's first 😁

**Comment by sfalkman** [comment]
Too slow :) Try it out now

**Comment by JohNan** [comment]
It works perfectly! Thank you!

**Comment by patrik3k** [comment]
Yes works lika a charm! Very well done. Is it possible to add it to the normal HACS integration directory. I added it with a Custom repository now.
